/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.alissonlima.designpatterns;

import br.com.alissonlima.designpatterns.domain.Cliente;
import br.com.alissonlima.designpatterns.domain.Conta;
import br.com.alissonlima.designpatterns.processos.MovimentacaoFinanceira;
import br.com.alissonlima.designpatterns.processos.MovimentacaoFinanceiraException;
import br.com.alissonlima.designpatterns.processos.MovimentacaoLogObserver;

import java.math.BigDecimal;

public class App {

    public static void main(String[] args) {
        Conta conta = criarContaFake();

        MovimentacaoFinanceira movimentacaoFinanceira = new MovimentacaoFinanceira();
        movimentacaoFinanceira.registerObserver(new MovimentacaoLogObserver());

        try {
            movimentacaoFinanceira.sacarValor(conta, new BigDecimal(10L));
        } catch (MovimentacaoFinanceiraException e) {
            e.printStackTrace();
        }
    }

    public static Cliente criarClienteFake(){
        return new Cliente.Builder()
                .withNome("Alisson")
                .withSobrenome("Lima")
                .withCidade("Camaqua")
                .withUf("RS")
                .withEmail("usuario@gmail.com")
                .withLogradouro("Rua Numero 1")
                .withTelefone("51 12345678")
                .build();

    }
    public static Conta criarContaFake(){
        return new Conta(criarClienteFake(), new BigDecimal(100l));
    }
}
